service: aws-lambda-starwars
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  environment:
    LAMBDA_PEOPLE_TABLE: ${self:custom.peopleTable}
    LAMBDA_NAMESPACE_ID: 1b671a64-40d5-491e-99b0-da01ff1f3341
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:*
    Resource:
      - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.peopleTable}

package: 
  individually: true

custom:
  peopleTable: ${sls:stage}-swapi-people-table

functions:
  createPerson:
    handler: src/functions/createPerson/index.createPerson
    events:
      - httpApi:
          path: /person/{id}
          method: post

  getPeople:
    handler: src/functions/getPeople/index.getPeople
    events:
      - httpApi:
          path: /person
          method: get

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.peopleTable}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
